shipSection('Lancaster') {
    SuperTime 1000
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    MultiFireEnergy 420
    BombFireEnergyUpgrade 0
    LandmineFireEnergyUpgrade 0
    SeeBombLevel 2
    DisableFastShooting 1
    Radius 0
    MultiFireAngle 555
    MaximumRotation 200
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 2750
    MaximumEnergy 1500
    InitialRotation 200
    InitialThrust 16
    InitialSpeed 1800
    InitialRecharge 2750
    InitialEnergy 1500
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 4750
    BombThrust 1000
    TurretThrustPenalty 3
    TurretSpeedPenalty 360
    MultiFireDelay 50
    InitialBounty 3
    DamageFactor 0
    PrizeShareLimit 0
    AttachBounty 3
    TurretLimit 1
    BurstShrapnel 1
    MaxMines 0
    BombBounceCount 0
    ShrapnelMax 0
    ShrapnelRate 0
    DoubleBarrel 1
    EmpBomb 0
    SeeMines 0
}
