; Turf Classic East
#include /conf/svs-tce/ship-javelin
#include /conf/svs-tce/ship-lancaster
#include /conf/svs-tce/ship-leviathan
#include /conf/svs-tce/ship-shark
#include /conf/svs-tce/ship-spider
#include /conf/svs-tce/ship-terrier
#include /conf/svs-tce/ship-warbird
#include /conf/svs-tce/ship-weasel
#include /conf/svs-tce/misc
#include /conf/svs-tce/prizeweights
#include /conf/svs-tce/cost
