{
  "formatVersion": "1.1",
  "component": {
    "group": "com.simsilica",
    "module": "mphys",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.simsilica",
          "module": "sim-math",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "mphys-1.0.0-SNAPSHOT.jar",
          "url": "mphys-1.0.0-SNAPSHOT.jar",
          "size": 103470,
          "sha512": "a18462d5046c7ec50c2a558187d26c54e0553e596277724a1e467372cacca566f856dfb19886cda29de38ed63fc5f40d54d328b65270f7fafbdda5bcfb293207",
          "sha256": "03d57193a64881ade113f2da96b843d48cb41f6c34433261bf8a92f7cb6fdabe",
          "sha1": "1796221a0f6b18aa81013a1c797e16f31b64c745",
          "md5": "a8b1147db2045b12abbf8a2412d28708"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "19.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "com.simsilica",
          "module": "sim-ethereal",
          "version": {
            "requires": "1.8.1-SNAPSHOT"
          }
        },
        {
          "group": "com.simsilica",
          "module": "sim-math",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "mphys-1.0.0-SNAPSHOT.jar",
          "url": "mphys-1.0.0-SNAPSHOT.jar",
          "size": 103470,
          "sha512": "a18462d5046c7ec50c2a558187d26c54e0553e596277724a1e467372cacca566f856dfb19886cda29de38ed63fc5f40d54d328b65270f7fafbdda5bcfb293207",
          "sha256": "03d57193a64881ade113f2da96b843d48cb41f6c34433261bf8a92f7cb6fdabe",
          "sha1": "1796221a0f6b18aa81013a1c797e16f31b64c745",
          "md5": "a8b1147db2045b12abbf8a2412d28708"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mphys-1.0.0-SNAPSHOT-javadoc.jar",
          "url": "mphys-1.0.0-SNAPSHOT-javadoc.jar",
          "size": 271790,
          "sha512": "1d4b6537e4dcb650f9e496748f300872b14d79ffae532350566aa59b550dc4a1bf7d8a2e07d57811f162ea1bc22cc41f77cb5e4ca30370811b956fabcb5aa0ce",
          "sha256": "310f63a760e229ec715577497b134f318bc032bd0a33c3ab9af654405fbecfe2",
          "sha1": "b79bcb2a38f05fb58cda33df4a7d0ca9f0417965",
          "md5": "f199e2c191f32bf5537bbd640d792893"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mphys-1.0.0-SNAPSHOT-sources.jar",
          "url": "mphys-1.0.0-SNAPSHOT-sources.jar",
          "size": 109895,
          "sha512": "b0211704f3e730f357ec5945d95b34fa50d8d849aa33dcbe58e8fcf72c04b82f2e32a2f047d24ca158a9d22ba28c7b6e25c2cfb195ad7a6145d4e67e93071e2c",
          "sha256": "beff2c00db363cc6a86cbb750a159e48196e5fd4b0e3347088e51d230691a3e5",
          "sha1": "ed05f031fc27c1e2cd588f9eb880e32ce613ee85",
          "md5": "2740f222bc6413b50a2ec67824e55d8b"
        }
      ]
    }
  ]
}
