{
  "formatVersion": "1.1",
  "component": {
    "group": "com.simsilica",
    "module": "mphys",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.simsilica",
          "module": "sim-math",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "mphys-1.0.0-SNAPSHOT.jar",
          "url": "mphys-1.0.0-SNAPSHOT.jar",
          "size": 103660,
          "sha512": "512fd5c763adf55b434d47f7f946e776d40c8cb880d414247a301d80629fd57b1eb5cbe736162ca91472a0321aa0165785139e72246f5f53b174f78caf93b5b6",
          "sha256": "e47b69d3b05bf1affddeb1779e7766899ece55fe8a510624c957ec16de09af66",
          "sha1": "d5cddfd1f0f2bec3198496b26bfbd6fa84abb918",
          "md5": "3a43575da5e27d21db03f55192bd986d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "19.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "com.simsilica",
          "module": "sim-ethereal",
          "version": {
            "requires": "1.8.1-SNAPSHOT"
          }
        },
        {
          "group": "com.simsilica",
          "module": "sim-math",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "mphys-1.0.0-SNAPSHOT.jar",
          "url": "mphys-1.0.0-SNAPSHOT.jar",
          "size": 103660,
          "sha512": "512fd5c763adf55b434d47f7f946e776d40c8cb880d414247a301d80629fd57b1eb5cbe736162ca91472a0321aa0165785139e72246f5f53b174f78caf93b5b6",
          "sha256": "e47b69d3b05bf1affddeb1779e7766899ece55fe8a510624c957ec16de09af66",
          "sha1": "d5cddfd1f0f2bec3198496b26bfbd6fa84abb918",
          "md5": "3a43575da5e27d21db03f55192bd986d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mphys-1.0.0-SNAPSHOT-javadoc.jar",
          "url": "mphys-1.0.0-SNAPSHOT-javadoc.jar",
          "size": 272366,
          "sha512": "8ba7c1e9d5abe8883392f4f75f2cfd6e86e8ecd5c4e64e8053cac234b0a5780d0c638367247cd82be071823b65c6b7462bbcd77f4e392555a589e578ed0cd46d",
          "sha256": "338dcf795341409324514c874439dd5cf75df1bbf265c0ba0055db58f8ec8521",
          "sha1": "29e773b76bf56d99728c91dc667141731643fe52",
          "md5": "147f87f38e67325aeec19a0107c52786"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mphys-1.0.0-SNAPSHOT-sources.jar",
          "url": "mphys-1.0.0-SNAPSHOT-sources.jar",
          "size": 110199,
          "sha512": "9f34b8dba05e6448a27f09403905ec7cb36eba23d0e9bd00de389dc1588b15e541b8b10bab6ee9d1d5fdc653fc1b70526cd6a411b5866a52e30d464a04596d08",
          "sha256": "0d36ac3c78f371908df0a5f4c8aa3a9a13e2097f413e3282bb83696eb858d4a5",
          "sha1": "a239a39ad555b63a9cc7c166edcaba507f2f0c35",
          "md5": "577a149381521b98172fcf73ec27969a"
        }
      ]
    }
  ]
}
