shipSection('Shark') {
    SuperTime 1000
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    MultiFireEnergy 32000
    BombFireEnergyUpgrade 0
    LandmineFireEnergyUpgrade 0
    BulletSpeed 1
    BombSpeed 1
    SeeBombLevel 2
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 0
    MaximumRotation 210
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 1500
    MaximumEnergy 1200
    InitialRotation 210
    InitialThrust 13
    InitialSpeed 1875
    InitialRecharge 1500
    InitialEnergy 1200
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 4000
    BombThrust 0
    BurstSpeed 1
    TurretThrustPenalty 4
    TurretSpeedPenalty 450
    MultiFireDelay 32000
    InitialBounty 3
    DamageFactor 0
    PrizeShareLimit 0
    AttachBounty 3
    TurretLimit 1
    BurstShrapnel 1
    MaxMines 4
    BombBounceCount 0
    ShrapnelMax 8
    ShrapnelRate 3
    DoubleBarrel 0
    EmpBomb 1
    SeeMines 1
}
