shipSection('Leviathan') {
    SuperTime 0
    ShieldsTime 3000
    Gravity 1000
    GravityTopSpeed 250
    MultiFireEnergy 40
    BombFireEnergyUpgrade 0
    LandmineFireEnergyUpgrade 0
    SeeBombLevel 1
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 1200
    MaximumRotation 300
    MaximumThrust 31
    MaximumSpeed 3350
    MaximumRecharge 4100
    MaximumEnergy 2500
    InitialRotation 280
    InitialThrust 28
    InitialSpeed 2300
    InitialRecharge 2600
    InitialEnergy 1500
    UpgradeRotation 100
    UpgradeThrust 9
    UpgradeSpeed 400
    UpgradeRecharge 700
    UpgradeEnergy 300
    AfterburnerEnergy 1
    BombThrust 0
    TurretThrustPenalty 0
    TurretSpeedPenalty 0
    MultiFireDelay 7
    InitialBounty 3
    DamageFactor 5000
    PrizeShareLimit 0
    AttachBounty 0
    TurretLimit 3
    BurstShrapnel 130
    MaxMines 4
    BombBounceCount 0
    ShrapnelMax 31
    ShrapnelRate 7
    DoubleBarrel 0
    EmpBomb 0
    SeeMines 1
}
