{
  "formatVersion": "1.1",
  "component": {
    "group": "com.simsilica",
    "module": "sio2-mphys",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.simsilica",
          "module": "sim-math",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "com.simsilica",
          "module": "sio2",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "com.simsilica",
          "module": "mphys",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "sio2-mphys-1.0.0-SNAPSHOT.jar",
          "url": "sio2-mphys-1.0.0-SNAPSHOT.jar",
          "size": 72980,
          "sha512": "58de993f09c038a8530db5e72abbc2b5f1bc75a99e83ff0f00aa1539b72de1a5ce1ebe2501611efea2dbab4d278894e92d7debae49eeb58ee46feb89f03be869",
          "sha256": "a059bbb314fa5c1d13b509fe07d56a538526ed1e2b77ee46a01fefb197f4f936",
          "sha1": "0f2297eda1699219e2d720b06ed0453ead0d14d0",
          "md5": "a3ad82158f4b45cb1a38de6da1e8ce97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "19.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "com.simsilica",
          "module": "sim-ethereal",
          "version": {
            "requires": "1.8.1-SNAPSHOT"
          }
        },
        {
          "group": "com.simsilica",
          "module": "sim-math",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "com.simsilica",
          "module": "sio2",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "com.simsilica",
          "module": "mphys",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "sio2-mphys-1.0.0-SNAPSHOT.jar",
          "url": "sio2-mphys-1.0.0-SNAPSHOT.jar",
          "size": 72980,
          "sha512": "58de993f09c038a8530db5e72abbc2b5f1bc75a99e83ff0f00aa1539b72de1a5ce1ebe2501611efea2dbab4d278894e92d7debae49eeb58ee46feb89f03be869",
          "sha256": "a059bbb314fa5c1d13b509fe07d56a538526ed1e2b77ee46a01fefb197f4f936",
          "sha1": "0f2297eda1699219e2d720b06ed0453ead0d14d0",
          "md5": "a3ad82158f4b45cb1a38de6da1e8ce97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sio2-mphys-1.0.0-SNAPSHOT-javadoc.jar",
          "url": "sio2-mphys-1.0.0-SNAPSHOT-javadoc.jar",
          "size": 176549,
          "sha512": "966db986df2dbb31a2622309e60dd256afda1494101412ee821c3840ae3c18574592805def949518e28dbfa9e22765671c52a99c5526802b2205fd9afa0e7b2c",
          "sha256": "fdbf4fe33284f36879efe3ef0fa4bd481529ffd66857ae57a21e0aa74690a24f",
          "sha1": "6408e1007d414801ead7716cc3b1754794565ceb",
          "md5": "f61e6dac7605e5df8f59c3b871e461b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sio2-mphys-1.0.0-SNAPSHOT-sources.jar",
          "url": "sio2-mphys-1.0.0-SNAPSHOT-sources.jar",
          "size": 54978,
          "sha512": "1008021e86e6c3819594b544608c62917b56b3f7a3f4ad2de323d5d6d265999166094f967368a35a82301e28f2d58e517545526795ee7dbff91b6c9533f0a7d7",
          "sha256": "fb87a2a0341771db296166e397f264e1bd1d82114750a63269c056aa0d55d9ab",
          "sha1": "56e5c338eb2d3b9dc865648752bd4d7874810687",
          "md5": "321876f4f936abb248f8829b3b18202a"
        }
      ]
    }
  ]
}
