shipSection('Weasel') {
    SuperTime 0
    ShieldsTime 3000
    Gravity 1000
    GravityTopSpeed 250
    BulletFireEnergy 27
    MultiFireEnergy 35
    BombFireEnergy 400
    BombFireEnergyUpgrade 0
    LandmineFireEnergy 250
    LandmineFireEnergyUpgrade 0
    BulletSpeed 3600
    BombSpeed 4850
    SeeBombLevel 0
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 990
    CloakEnergy 0
    StealthEnergy 0
    AntiWarpEnergy 1300
    XRadarEnergy 0
    MaximumRotation 360
    MaximumThrust 31
    MaximumSpeed 3500
    MaximumRecharge 3800
    MaximumEnergy 3000
    InitialRotation 300
    InitialThrust 25
    InitialSpeed 2900
    InitialRecharge 2700
    InitialEnergy 1400
    UpgradeRotation 100
    UpgradeThrust 7
    UpgradeSpeed 250
    UpgradeRecharge 550
    UpgradeEnergy 400
    AfterburnerEnergy 1
    BombThrust 0
    BurstSpeed 8000
    TurretThrustPenalty 0
    TurretSpeedPenalty 20
    BulletFireDelay 5
    MultiFireDelay 10
    BombFireDelay 175
    LandmineFireDelay 36
    RocketTime 1000
    InitialBounty 3
    DamageFactor 5000
    PrizeShareLimit 0
    AttachBounty 0
    TurretLimit 5
    BurstShrapnel 130
    MaxMines 3
    RepelMax 1
    BurstMax 2
    DecoyMax 2
    ThorMax 0
    BrickMax 0
    PortalMax 0
    RocketMax 0
    InitialRepel 0
    InitialBurst 0
    InitialBrick 0
    InitialRocket 0
    InitialThor 0
    InitialDecoy 0
    InitialPortal 0
    BombBounceCount 0
    ShrapnelMax 16
    ShrapnelRate 3
    CloakStatus 0
    StealthStatus 1
    XRadarStatus 1
    AntiWarpStatus 0
    InitialGuns 2
    MaxGuns 3
    InitialBombs 3
    MaxBombs 3
    DoubleBarrel 1
    EmpBomb 1
    SeeMines 1
}
