shipSection('Leviathan') {
    SuperTime 0
    ShieldsTime 3000
    Gravity 1000
    GravityTopSpeed 250
    BulletFireEnergy 30
    MultiFireEnergy 40
    BombFireEnergy 600
    BombFireEnergyUpgrade 0
    LandmineFireEnergy 625
    LandmineFireEnergyUpgrade 0
    BulletSpeed 4000
    BombSpeed 5000
    SeeBombLevel 1
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 1200
    CloakEnergy 0
    StealthEnergy 1
    AntiWarpEnergy 1100
    XRadarEnergy 0
    MaximumRotation 300
    MaximumThrust 31
    MaximumSpeed 3350
    MaximumRecharge 4100
    MaximumEnergy 2500
    InitialRotation 280
    InitialThrust 28
    InitialSpeed 2300
    InitialRecharge 2600
    InitialEnergy 1500
    UpgradeRotation 100
    UpgradeThrust 9
    UpgradeSpeed 400
    UpgradeRecharge 700
    UpgradeEnergy 300
    AfterburnerEnergy 1
    BombThrust 0
    BurstSpeed 8000
    TurretThrustPenalty 0
    TurretSpeedPenalty 0
    BulletFireDelay 6
    MultiFireDelay 7
    BombFireDelay 45
    LandmineFireDelay 36
    RocketTime 1000
    InitialBounty 3
    DamageFactor 5000
    PrizeShareLimit 0
    AttachBounty 0
    TurretLimit 3
    BurstShrapnel 130
    MaxMines 4
    RepelMax 3
    BurstMax 2
    DecoyMax 3
    ThorMax 0
    BrickMax 0
    PortalMax 0
    RocketMax 0
    InitialRepel 0
    InitialBurst 0
    InitialBrick 0
    InitialRocket 0
    InitialThor 0
    InitialDecoy 0
    InitialPortal 0
    BombBounceCount 0
    ShrapnelMax 31
    ShrapnelRate 7
    CloakStatus 0
    StealthStatus 1
    XRadarStatus 1
    AntiWarpStatus 0
    InitialGuns 3
    MaxGuns 3
    InitialBombs 2
    MaxBombs 3
    DoubleBarrel 0
    EmpBomb 0
    SeeMines 1
}
