shipSection('Javelin') {
    SuperTime 0
    ShieldsTime 3000
    Gravity 1000
    GravityTopSpeed 250
    BulletFireEnergy 27
    MultiFireEnergy 30
    BombFireEnergy 510
    BombFireEnergyUpgrade 0
    LandmineFireEnergy 500
    LandmineFireEnergyUpgrade 0
    BulletSpeed 3300
    BombSpeed 4300
    SeeBombLevel 0
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 1300
    CloakEnergy 0
    StealthEnergy 1
    AntiWarpEnergy 1100
    XRadarEnergy 0
    MaximumRotation 310
    MaximumThrust 31
    MaximumSpeed 3400
    MaximumRecharge 3500
    MaximumEnergy 2000
    InitialRotation 290
    InitialThrust 24
    InitialSpeed 2950
    InitialRecharge 2500
    InitialEnergy 1000
    UpgradeRotation 100
    UpgradeThrust 7
    UpgradeSpeed 400
    UpgradeRecharge 700
    UpgradeEnergy 300
    AfterburnerEnergy 1
    BombThrust 0
    BurstSpeed 8000
    TurretThrustPenalty 0
    TurretSpeedPenalty 0
    BulletFireDelay 6
    MultiFireDelay 6
    BombFireDelay 25
    LandmineFireDelay 36
    RocketTime 1000
    InitialBounty 3
    DamageFactor 5000
    PrizeShareLimit 0
    AttachBounty 0
    SoccerBallFriction 10
    SoccerBallProximity 50
    SoccerThrowTime 2500
    SoccerBallSpeed 2500
    TurretLimit 3
    BurstShrapnel 130
    MaxMines 3
    RepelMax 2
    BurstMax 2
    DecoyMax 3
    ThorMax 0
    BrickMax 0
    PortalMax 0
    RocketMax 0
    InitialRepel 0
    InitialBurst 0
    InitialBrick 0
    InitialRocket 0
    InitialThor 0
    InitialDecoy 1
    InitialPortal 0
    BombBounceCount 1
    ShrapnelMax 31
    ShrapnelRate 7
    CloakStatus 0
    StealthStatus 0
    XRadarStatus 1
    AntiWarpStatus 0
    InitialGuns 3
    MaxGuns 3
    InitialBombs 3
    MaxBombs 3
    DoubleBarrel 0
    EmpBomb 0
    SeeMines 0
}
