shipSection('Terrier') {
    SuperTime 0
    ShieldsTime 3000
    Gravity 1000
    GravityTopSpeed 250
    MultiFireEnergy 45
    BombFireEnergyUpgrade 0
    LandmineFireEnergyUpgrade 0
    BulletSpeed 3200
    BombSpeed 4300
    SeeBombLevel 0
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 500
    CloakEnergy 0
    StealthEnergy 0
    AntiWarpEnergy 1300
    XRadarEnergy 0
    MaximumRotation 300
    MaximumThrust 31
    MaximumSpeed 3400
    MaximumRecharge 3800
    MaximumEnergy 2800
    InitialRotation 280
    InitialThrust 30
    InitialSpeed 2950
    InitialRecharge 2650
    InitialEnergy 1600
    UpgradeRotation 100
    UpgradeThrust 7
    UpgradeSpeed 300
    UpgradeRecharge 700
    UpgradeEnergy 400
    AfterburnerEnergy 1
    BombThrust 0
    BurstSpeed 8000
    TurretThrustPenalty 0
    TurretSpeedPenalty 40
    MultiFireDelay 10
    InitialBounty 3
    DamageFactor 5000
    PrizeShareLimit 0
    AttachBounty 0
    TurretLimit 3
    BurstShrapnel 130
    MaxMines 2
    BombBounceCount 3
    ShrapnelMax 16
    ShrapnelRate 3
    CloakStatus 0
    StealthStatus 1
    XRadarStatus 2
    AntiWarpStatus 0
    DoubleBarrel 1
    EmpBomb 0
    SeeMines 0
}
