shipSection('Shark') {
    SuperTime 0
    ShieldsTime 3000
    Gravity 1000
    GravityTopSpeed 250
    BulletFireEnergy 29
    MultiFireEnergy 29
    BombFireEnergy 320
    BombFireEnergyUpgrade 0
    LandmineFireEnergy 500
    LandmineFireEnergyUpgrade 0
    BulletSpeed 3000
    BombSpeed 4900
    SeeBombLevel 0
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 1000
    CloakEnergy 900
    StealthEnergy 1
    AntiWarpEnergy 1350
    XRadarEnergy 0
    MaximumRotation 320
    MaximumThrust 31
    MaximumSpeed 3500
    MaximumRecharge 3800
    MaximumEnergy 2900
    InitialRotation 300
    InitialThrust 30
    InitialSpeed 2850
    InitialRecharge 2500
    InitialEnergy 1600
    UpgradeRotation 100
    UpgradeThrust 7
    UpgradeSpeed 250
    UpgradeRecharge 500
    UpgradeEnergy 400
    AfterburnerEnergy 1
    BombThrust 0
    BurstSpeed 8000
    TurretThrustPenalty 0
    TurretSpeedPenalty 30
    BulletFireDelay 8
    MultiFireDelay 10
    BombFireDelay 180
    LandmineFireDelay 36
    RocketTime 500
    InitialBounty 3
    DamageFactor 5000
    PrizeShareLimit 0
    AttachBounty 0
    SoccerBallFriction 10
    SoccerBallProximity 50
    SoccerThrowTime 2500
    SoccerBallSpeed 2500
    TurretLimit 2
    BurstShrapnel 130
    MaxMines 2
    RepelMax 2
    BurstMax 3
    DecoyMax 2
    ThorMax 0
    BrickMax 0
    PortalMax 0
    RocketMax 0
    InitialRepel 0
    InitialBurst 0
    InitialBrick 0
    InitialRocket 0
    InitialThor 0
    InitialDecoy 0
    InitialPortal 0
    BombBounceCount 0
    ShrapnelMax 16
    ShrapnelRate 3
    CloakStatus 2
    StealthStatus 1
    XRadarStatus 1
    AntiWarpStatus 0
    InitialGuns 2
    MaxGuns 3
    InitialBombs 3
    MaxBombs 3
    DoubleBarrel 1
    EmpBomb 1
    SeeMines 0
}
