title: Subspace Infinity
description: Subspace Continuum, reimagined in Java — pre-alpha
theme: jekyll-theme-cayman
url: https://assofohdz.github.io
baseurl: /Subspace-Infinity
repository: assofohdz/Subspace-Infinity
show_downloads: false
