; SVS league settings based on http://forum.svssubspace.com/showthread.php?tid=14496 and a lot of guesswork

#include /conf/svs-league/ship-javelin
#include /conf/svs-league/ship-lancaster
#include /conf/svs-league/ship-leviathan
#include /conf/svs-league/ship-shark
#include /conf/svs-league/ship-spider
#include /conf/svs-league/ship-terrier
#include /conf/svs-league/ship-warbird
#include /conf/svs-league/ship-weasel
#include /conf/svs-league/misc
#include /conf/svs-league/prizeweights
#include /conf/svs-league/cost
