shipSection('Weasel') {
    SuperTime 1000
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    BulletFireEnergy 208
    MultiFireEnergy 242
    BombFireEnergy 32000
    BombFireEnergyUpgrade 0
    LandmineFireEnergy 32000
    LandmineFireEnergyUpgrade 0
    BulletSpeed 1000
    BombSpeed 5000
    SeeBombLevel 1
    DisableFastShooting 0
    Radius 7
    MultiFireAngle 250
    CloakEnergy 1250
    StealthEnergy 400
    AntiWarpEnergy 32000
    XRadarEnergy 32000
    MaximumRotation 130
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 1250
    MaximumEnergy 1020
    InitialRotation 130
    InitialThrust 18
    InitialSpeed 1100
    InitialRecharge 1250
    InitialEnergy 1020
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 5200
    BombThrust 1000
    BurstSpeed 1
    TurretThrustPenalty 5
    TurretSpeedPenalty 220
    BulletFireDelay 40
    MultiFireDelay 40
    BombFireDelay 30
    LandmineFireDelay 20
    RocketTime 80
    InitialBounty 3
    DamageFactor 2000
    PrizeShareLimit 0
    AttachBounty 3
    TurretLimit 0
    BurstShrapnel 1
    MaxMines 0
    RepelMax 1
    BurstMax 0
    DecoyMax 1
    ThorMax 3
    BrickMax 2
    PortalMax 0
    RocketMax 1
    InitialRepel 0
    InitialBurst 0
    InitialBrick 0
    InitialRocket 0
    InitialThor 0
    InitialDecoy 0
    InitialPortal 0
    BombBounceCount 0
    ShrapnelMax 0
    ShrapnelRate 0
    CloakStatus 2
    StealthStatus 2
    XRadarStatus 0
    AntiWarpStatus 0
    InitialGuns 3
    MaxGuns 3
    InitialBombs 0
    MaxBombs 0
    DoubleBarrel 0
    EmpBomb 0
    SeeMines 0
}
