shipSection('Spider') {
    SuperTime 1000
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    MultiFireEnergy 225
    BombFireEnergyUpgrade 0
    LandmineFireEnergyUpgrade 0
    SeeBombLevel 2
    DisableFastShooting 1
    Radius 0
    MultiFireAngle 0
    MaximumRotation 180
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 2500
    MaximumEnergy 1400
    InitialRotation 180
    InitialThrust 18
    InitialSpeed 1700
    InitialRecharge 2500
    InitialEnergy 1400
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 6200
    BombThrust 1000
    TurretThrustPenalty 5
    TurretSpeedPenalty 340
    MultiFireDelay 35
    InitialBounty 3
    DamageFactor 0
    PrizeShareLimit 0
    AttachBounty 3
    TurretLimit 1
    BurstShrapnel 1
    MaxMines 0
    BombBounceCount 0
    ShrapnelMax 0
    ShrapnelRate 0
    DoubleBarrel 0
    EmpBomb 0
    SeeMines 0
}
