shipSection('Javelin') {
    SuperTime 1000
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    BulletFireEnergy 300
    MultiFireEnergy 300
    BombFireEnergy 1100
    BombFireEnergyUpgrade 0
    LandmineFireEnergy 32000
    LandmineFireEnergyUpgrade 0
    BulletSpeed 64636
    BombSpeed 2250
    SeeBombLevel 2
    DisableFastShooting 1
    Radius 0
    MultiFireAngle 2000
    CloakEnergy 600
    StealthEnergy 2000
    AntiWarpEnergy 2000
    XRadarEnergy 2000
    MaximumRotation 200
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 1500
    MaximumEnergy 1500
    InitialRotation 200
    InitialThrust 13
    InitialSpeed 1900
    InitialRecharge 1500
    InitialEnergy 1500
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 5000
    BombThrust 50
    BurstSpeed 1
    TurretThrustPenalty 3
    TurretSpeedPenalty 380
    BulletFireDelay 60
    MultiFireDelay 150
    BombFireDelay 75
    LandmineFireDelay 20
    RocketTime 400
    InitialBounty 3
    DamageFactor 0
    PrizeShareLimit 0
    AttachBounty 3
    TurretLimit 1
    BurstShrapnel 1
    MaxMines 0
    RepelMax 0
    BurstMax 0
    DecoyMax 1
    ThorMax 3
    BrickMax 0
    PortalMax 0
    RocketMax 3
    InitialRepel 0
    InitialBurst 0
    InitialBrick 0
    InitialRocket 1
    InitialThor 0
    InitialDecoy 0
    InitialPortal 0
    BombBounceCount 1
    ShrapnelMax 15
    ShrapnelRate 3
    CloakStatus 0
    StealthStatus 0
    XRadarStatus 0
    AntiWarpStatus 0
    InitialGuns 1
    MaxGuns 1
    InitialBombs 1
    MaxBombs 1
    DoubleBarrel 0
    EmpBomb 0
    SeeMines 1
}
