shipSection('Leviathan') {
    SuperTime 0
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    MultiFireEnergy 400
    BombFireEnergyUpgrade 0
    LandmineFireEnergyUpgrade 0
    SeeBombLevel 2
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 4440
    MaximumRotation 800
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 32000
    MaximumEnergy 1500
    InitialRotation 45
    InitialThrust 5
    InitialSpeed 500
    InitialRecharge 1100
    InitialEnergy 1500
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 12000
    BombThrust 100
    TurretThrustPenalty 0
    TurretSpeedPenalty 0
    MultiFireDelay 100
    InitialBounty 3
    DamageFactor 3000
    PrizeShareLimit 15
    AttachBounty 20
    TurretLimit 0
    BurstShrapnel 1
    MaxMines 1
    BombBounceCount 0
    ShrapnelMax 0
    ShrapnelRate 0
    DoubleBarrel 1
    EmpBomb 0
    SeeMines 1
}
