shipSection('Leviathan') {
    SuperTime 0
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    BulletFireEnergy 400
    MultiFireEnergy 400
    BombFireEnergy 1100
    BombFireEnergyUpgrade 0
    LandmineFireEnergy 800
    LandmineFireEnergyUpgrade 0
    BulletSpeed 1000
    BombSpeed 4000
    SeeBombLevel 2
    DisableFastShooting 0
    Radius 0
    MultiFireAngle 4440
    CloakEnergy 600
    StealthEnergy 1000
    AntiWarpEnergy 2000
    XRadarEnergy 2000
    MaximumRotation 800
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 32000
    MaximumEnergy 1500
    InitialRotation 45
    InitialThrust 5
    InitialSpeed 500
    InitialRecharge 1100
    InitialEnergy 1500
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 12000
    BombThrust 100
    BurstSpeed 1
    TurretThrustPenalty 0
    TurretSpeedPenalty 0
    BulletFireDelay 60
    MultiFireDelay 100
    BombFireDelay 75
    LandmineFireDelay 20
    RocketTime 180
    InitialBounty 3
    DamageFactor 3000
    PrizeShareLimit 15
    AttachBounty 20
    TurretLimit 0
    BurstShrapnel 1
    MaxMines 1
    RepelMax 4
    BurstMax 0
    DecoyMax 3
    ThorMax 0
    BrickMax 0
    PortalMax 1
    RocketMax 0
    InitialRepel 4
    InitialBurst 0
    InitialBrick 0
    InitialRocket 0
    InitialThor 0
    InitialDecoy 0
    InitialPortal 1
    BombBounceCount 0
    ShrapnelMax 0
    ShrapnelRate 0
    CloakStatus 0
    StealthStatus 2
    XRadarStatus 0
    AntiWarpStatus 0
    InitialGuns 2
    MaxGuns 2
    InitialBombs 3
    MaxBombs 3
    DoubleBarrel 1
    EmpBomb 0
    SeeMines 1
}
