shipSection('Javelin') {
    SuperTime 1000
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    MultiFireEnergy 300
    BombFireEnergyUpgrade 0
    LandmineFireEnergyUpgrade 0
    SeeBombLevel 2
    DisableFastShooting 1
    Radius 0
    MultiFireAngle 2000
    MaximumRotation 200
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 1500
    MaximumEnergy 1500
    InitialRotation 200
    InitialThrust 13
    InitialSpeed 1900
    InitialRecharge 1500
    InitialEnergy 1500
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 5000
    BombThrust 50
    TurretThrustPenalty 3
    TurretSpeedPenalty 380
    MultiFireDelay 150
    InitialBounty 3
    DamageFactor 0
    PrizeShareLimit 0
    AttachBounty 3
    TurretLimit 1
    BurstShrapnel 1
    MaxMines 0
    BombBounceCount 1
    ShrapnelMax 15
    ShrapnelRate 3
    DoubleBarrel 0
    EmpBomb 0
    SeeMines 1
}
