shipSection('Warbird') {
    SuperTime 1000
    ShieldsTime 6000
    Gravity 1500
    GravityTopSpeed 100
    MultiFireEnergy 450
    BombFireEnergyUpgrade 0
    LandmineFireEnergyUpgrade 0
    BulletSpeed 5000
    BombSpeed 5000
    SeeBombLevel 2
    DisableFastShooting 1
    Radius 0
    MultiFireAngle 0
    AntiWarpEnergy 2000
    XRadarEnergy 2000
    MaximumRotation 200
    MaximumThrust 24
    MaximumSpeed 6000
    MaximumRecharge 4000
    MaximumEnergy 1500
    InitialRotation 200
    InitialThrust 16
    InitialSpeed 2000
    InitialRecharge 4000
    InitialEnergy 1500
    UpgradeRotation 0
    UpgradeThrust 0
    UpgradeSpeed 0
    UpgradeRecharge 0
    UpgradeEnergy 0
    AfterburnerEnergy 5500
    BombThrust 1000
    BurstSpeed 1
    TurretThrustPenalty 4
    TurretSpeedPenalty 400
    MultiFireDelay 100
    InitialBounty 3
    DamageFactor 0
    PrizeShareLimit 0
    AttachBounty 3
    TurretLimit 1
    BurstShrapnel 1
    MaxMines 0
    BombBounceCount 0
    ShrapnelMax 0
    ShrapnelRate 0
    XRadarStatus 0
    AntiWarpStatus 0
    DoubleBarrel 0
    EmpBomb 0
    SeeMines 0
}
