; Trench — April 2026 snapshot
; Trench Wars style zone tuning; 8 ships + prize weights.

#include /conf/trench-04-2026/prizeweights
#include /conf/trench-04-2026/ship-warbird
#include /conf/trench-04-2026/ship-javelin
#include /conf/trench-04-2026/ship-spider
#include /conf/trench-04-2026/ship-leviathan
#include /conf/trench-04-2026/ship-terrier
#include /conf/trench-04-2026/ship-weasel
#include /conf/trench-04-2026/ship-lancaster
#include /conf/trench-04-2026/ship-shark
#include /conf/trench-04-2026/misc
