name: Lint Workflows

on:
  push:
    branches: [ "infinity" ]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [ "infinity" ]
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run actionlint
        uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
        with:
          reporter: github-check
          fail_level: error
